const express = require('express');
const router = express.Router();

const ClienteController = require('../controllers/clienteController');
const funcionarioController = require('../controllers/funcionarioController');
const servicoController = require('../controllers/servicoController');
const eventoController = require('../controllers/eventoController');
const agendamentoController = require('../controllers/agendamentoController');


router.get('/', agendamentoController.listarTodos);
router.get('/disponiveis', agendamentoController.buscarDisponiveis);
router.get('/data/:data', agendamentoController.buscarPorData);
router.get('/:id', agendamentoController.buscarPorId);
router.get('/funcionario/:funcionarioId', agendamentoController.buscarPorFuncionario);
router.get('/evento/:eventoId', agendamentoController.buscarPorEvento);
router.post('/', agendamentoController.criar);
router.put('/:id', agendamentoController.atualizar);
router.delete('/:id', agendamentoController.deletar);
router.patch('/:id/disponibilidade', agendamentoController.alterarDisponibilidade);
router.post('/', ClienteController.criar);
router.get('/', ClienteController.listar);
router.get('/:id', ClienteController.buscarPorId);
router.put('/:id', ClienteController.atualizar);
router.delete('/:id', ClienteController.deletar);
router.post('/login', ClienteController.login);
router.get('/', eventoController.listarTodos);
router.get('/:id', eventoController.buscarPorId);
router.get('/cliente/:clienteId', eventoController.buscarPorCliente);
router.post('/', eventoController.criar);
router.put('/:id', eventoController.atualizar);
router.delete('/:id', eventoController.deletar);
router.post('/:id/funcionarios', eventoController.adicionarFuncionario);
router.delete('/:eventoId/funcionarios/:funcionarioId', eventoController.removerFuncionario);
router.get('/:id/funcionarios', eventoController.listarFuncionarios);
router.post('/:id/servicos', eventoController.adicionarServico);
router.delete('/:eventoId/servicos/:servicoId', eventoController.removerServico);
router.get('/:id/servicos', eventoController.listarServicos);
router.get('/', funcionarioController.index);
router.get('/:id', funcionarioController.show);
router.post('/', funcionarioController.store);
router.put('/:id', funcionarioController.update);
router.delete('/:id', funcionarioController.destroy);
router.get('/:id/eventos', funcionarioController.eventos);
router.get('/:id/agendamentos', funcionarioController.agendamentos);
router.get('/:id/disponibilidade', funcionarioController.verificarDisponibilidade);
router.get('/', servicoController.buscarTodos);
router.get('/:id', servicoController.buscarPorId);
router.post('/', servicoController.criar);
router.put('/:id', servicoController.atualizar);
router.delete('/:id', servicoController.deletar);
router.post('/calcular-custo', servicoController.calcularCustoTotal);

module.exports = router;
